### ISSUE TITLE
Project fails to build with error "Cannot find module './insertCss.js'" after upgrading to 5.0

### ISSUE THREAD

**Issue by mglace** [kriasoft/isomorphic-style-loader#146]
After upgrading my project to version 5.0.0 of the isomorphic-style-loader, I receive the following build error:
```
    Error: Cannot find module './insertCss.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
        at Function.resolve (internal/modules/cjs/helpers.js:32:19)
        at Object.resolve (C:\[...]\node_modules\isomorphic-style-loader\src\index.js:18:29)
```
Upon investigating, I found that the insertCss.js file is missing from the node_modules\isomorphic-style-loader folder.

**Comment by frenzzy** [comment]
Whoops! Forgot to include that file into npm package. Thanks for the testing :)
Should be fixed in v5.0.1. Please reopen if it is not.

**Comment by mglace** [comment]
@frenzzy - Thanks for your prompt response!
